import React,{useEffect,useRef,useState} from 'react';
import {stages,statuses,evidence,dayPlans,tasks as seedTasks} from './data.js';
import {knowledge,researchQuestions} from './knowledge.js';
import {counts,validateEdit} from './model.js';

export function Icon({name,size=20}){
 const paths={cycle:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 10h18"/></>,book:<><path d="M12 5v16M3 3c4-1 7 0 9 2 3-2 6-3 9-2v16c-4-1-6 0-9 2-3-2-6-3-9-2z"/></>,file:<><path d="M14 2H5v20h14V7zM14 2v5h5M8 12h8M8 16h8"/></>,arrow:<path d="m9 5 7 7-7 7"/>,search:<><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,folder:<path d="M3 6h6l2 3h10v12H3z"/>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
export function Status({value}){return <span className={`status ${value}`}><i/>{statuses[value]}</span>;}
export function Timeline({onDay}){return <section className="timeline" aria-label="两周时间轴"><div className="line-title"><span>10.08 — 10.21 · 14天推进计划</span><small>自然日 · 从当前基线补齐</small></div><div className="days">{dayPlans.map((d,i)=><button key={i} title={d[0]} onClick={()=>onDay(i+1)} aria-label={`第${i+1}天 ${d[0]}`}><i className={i===0?'today':''}/><span>10.{String(i+8).padStart(2,'0')}</span></button>)}</div></section>;}
export function Lifecycle({tasks,onSelect,onDay}){
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[expanded,setExpanded]=useState('01');
 const n=counts(tasks);const shown=tasks.filter(t=>(filter==='all'||t.status===filter)&&`${t.id} ${t.title} ${t.proof} ${t.acceptance}`.toLowerCase().includes(search.toLowerCase()));
 return <><div className="metrics">{['done','verify','todo','decision'].map(s=><button key={s} onClick={()=>setFilter(filter===s?'all':s)} aria-pressed={filter===s}><span>{statuses[s]}</span><strong>{n[s]}</strong></button>)}<div className="metric-mini">{n.doing} 项进行中<br/>{tasks.length} 项独立交付</div></div><Timeline onDay={onDay}/>
 <div className="section-head"><h2>阶段与交付物</h2><div className="filters"><label className="search"><Icon name="search" size={18}/><input aria-label="搜索任务" placeholder="搜索任务" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="状态筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div>
 <div className="stage-list">{stages.map(s=>{const items=shown.filter(t=>t.stage===s.id),all=tasks.filter(t=>t.stage===s.id),done=all.filter(t=>t.status==='done').length,open=expanded===s.id||search||filter!=='all';return items.length>0&&<section className="stage" key={s.id}><button className="stage-heading" onClick={()=>setExpanded(expanded===s.id?'':s.id)} aria-expanded={Boolean(open)}><span className={open?'chevron open':'chevron'}><Icon name="arrow" size={16}/></span><span className="stage-number">{s.id}</span><span>{s.title}</span><small>{done}/{all.length} 已验收</small><span className="mini-progress"><i style={{width:`${done/all.length*100}%`}}/></span></button>{open&&<div className="stage-body"><p className="gate">阶段出口 · {s.gate}</p><div className="task-table"><div className="table-heading"><span>任务 / 交付物</span><span>状态</span><span>计划</span><span>验收</span></div>{items.map(t=><button className="task-row" key={t.id} onClick={()=>onSelect(t.id)}><span><small>{t.id}</small><b>{t.title}</b><em>{t.deliverable}</em></span><Status value={t.status}/><span className="due">{t.due.slice(5).replace('-','.')}</span><span className="review-link">查看<Icon name="arrow" size={13}/></span></button>)}</div></div>}</section>})}{!shown.length&&<p className="empty">没有匹配项。试试其他关键词或状态。</p>}</div>
 <p className="footnote">已验收只计独立交付，不代表整个阶段通过。角色是职责建议，不代表已有团队成员。持续维护与下线不纳入本轮。</p></>;
}
export function Sprint({tasks,selected,onSelect}){return <><div className="note-band"><b>先补事实，再过关口。</b><span>14 天是计划，不是通过承诺。设备、真实用户、渠道与凭据方案需要你落实；关口失败就保留未完成。</span></div><div className="sprint-grid">{dayPlans.map(([title,desc],i)=>{const items=tasks.filter(t=>t.due===`2026-10-${String(i+8).padStart(2,'0')}`);return <section id={`day-${i+1}`} className={`day-plan ${selected===i+1?'selected':''}`} key={title}><div className="day-heading"><span>D{String(i+1).padStart(2,'0')}</span><small>10.{i+8}</small></div><div><h2>{title}</h2><p>{desc}</p><ul>{items.map(t=><li key={t.id}><button onClick={()=>onSelect(t.id)}><Status value={t.status}/><span>{t.title}</span><small>{t.id}</small></button></li>)}</ul>{!items.length&&<small>本日没有排定任务。</small>}</div></section>})}</div><section className="note-band"><b>排期边界</b><span>按自然日排定，尚待容量评审。改动任务日期会同步此视图；本轮不新增商城、森林、社交或长期运营。</span></section></>;}
export function Library(){const [topic,setTopic]=useState('全部');return <><div className="note-band"><b>书目已核验，不冒充读完。</b><span>为后续行业调研与 PRD 建立知识底稿；当前没有市场规模结论、用户研究结果或心理疗效结论。</span></div><div className="section-head"><h2>11 项基础与专题资料</h2><select aria-label="知识主题" value={topic} onChange={e=>setTopic(e.target.value)}>{['全部',...new Set(knowledge.map(k=>k.topic))].map(t=><option key={t}>{t}</option>)}</select></div><div className="book-list">{knowledge.filter(k=>topic==='全部'||k.topic===topic).map(k=><article key={k.id}><div className="book-index">{k.id}<small>{k.kind}</small></div><div><div className="book-title"><h2><a href={k.url} target="_blank" rel="noreferrer">{k.title}</a></h2><span>{k.priority}</span></div><p className="author">{k.author} · {k.topic}</p><p>{k.use}</p><details><summary>阅读路径与项目转化</summary><dl><dt>重点阅读</dt><dd>{k.reading}</dd><dt>落地产物</dt><dd>{k.output}</dd><dt>要回答的问题</dt><dd>{k.question}</dd><dt>来源与访问</dt><dd>{k.access} 检索日期 {k.checked}。</dd></dl></details></div></article>)}</div><section className="research"><h2>下一份调研与 PRD，要回答什么？</h2>{researchQuestions.map(([title,text,input])=><div key={title}><h3>{title}</h3><p>{text}</p><small>所需输入 · {input}</small></div>)}</section></>;}
export function Evidence(){return <><div className="note-band"><b>当前仍是 MVP，不是公开发布包。</b><span>87,447,911 bytes · 约 83.40 MiB · 0.3.0 (3)。不展示私有配置，不提供含本地凭据的 APK。</span></div><div className="evidence-list">{evidence.map(e=><article key={e.id}><div className="evidence-preview">{e.type==='截图'?<a href={`/evidence/${e.file}`} target="_blank" rel="noreferrer"><img src={`/evidence/${e.file}`} alt={e.title} loading="lazy"/></a>:e.type==='视频'?<video controls preload="metadata" src={`/evidence/${e.file}`} aria-label={e.title}/>:<div className="document-cover"><Icon name="file" size={32}/><span>{e.type}</span></div>}</div><div><small>{e.id} · {e.type} · {e.date}</small><h2>{e.title}</h2><p>{e.finding}</p><p className="limit">验收边界 · {e.limit}</p><a href={`/evidence/${e.file}`} target="_blank" rel="noreferrer">打开原始证据</a><details><summary>项目来源路径</summary><code>{e.source}</code></details></div></article>)}</div></>;}

export function TaskDrawer({task:current,tasks,onSave,onClose}){
 const task=seedTasks.find(t=>t.id===current.id);
 const [draft,setDraft]=useState({...current}),[error,setError]=useState('');const panel=useRef(null),close=useRef(null);
 useEffect(()=>{const previous=document.activeElement;close.current.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const focusable=Array.from(panel.current.querySelectorAll('button,input,select,textarea,a'));const a=focusable[0],b=focusable.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus();}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 const field=(name,value)=>setDraft({...draft,[name]:value});
 return <div className="scrim" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="task-title" ref={panel}><header><small>{task.id} · {stages.find(s=>s.id===task.stage).title}</small><button ref={close} onClick={onClose} aria-label="关闭详情"><Icon name="close"/></button></header><h2 id="task-title">{task.title}</h2><form onSubmit={e=>{e.preventDefault();const err=validateEdit(draft,tasks);if(err)setError(err);else onSave(task.id,draft);}}><div className="form-row"><label>当前状态<select value={draft.status} onChange={e=>field('status',e.target.value)}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>计划日期<input type="date" required value={draft.due} onChange={e=>field('due',e.target.value)}/></label></div><label>负责角色<input value={draft.owner} onChange={e=>field('owner',e.target.value)}/></label><section className="acceptance"><h3>通过条件</h3><p>{task.acceptance}</p><small>交付物 · {task.deliverable}</small></section><section className="baseline"><h3>当前证据基线 <Status value={task.baselineStatus}/></h3><p>{task.proof||'尚无已核验产物。'}</p><small>2026.10.08 基线不因手动更新而改写。</small></section>{task.deps.length>0&&<section><h3>前置任务</h3><ul className="dependencies">{task.deps.map(id=>{const t=tasks.find(x=>x.id===id);return <li key={id}><span>{id} {t?.title}</span><Status value={t?.status||'todo'}/></li>})}</ul></section>}<label>验收证据<textarea rows="3" value={draft.proof} onChange={e=>field('proof',e.target.value)} placeholder="填写实际产物路径、验证结果与日期"/></label><label>复核备注<textarea rows="3" value={draft.notes} onChange={e=>field('notes',e.target.value)} placeholder="进展、未通过原因、下一步"/></label>{error&&<p role="alert" className="error">{error}</p>}<footer><button className="primary" type="submit">保存修改</button><button type="button" onClick={onClose}>取消</button></footer><small className="footnote">手动更新是你的工作记录，不会自动重新运行 Unity 或验证证据。</small></form></aside></div>;
}
