export const knowledge = [
  {id:'K01',kind:'教材',title:'Software Engineering · 10th',author:'Ian Sommerville · Pearson',topic:'软件工程',priority:'先读',url:'https://www.pearson.com/en-us/subject-catalog/p/learning-theories-an-educational-perspective/P200000003258',reading:'第 2–6 章：过程、敏捷、需求、系统建模、架构；随后按测试与项目管理主题补读。',use:'把已有 Unity 实现放回“需求—设计—开发—验收”的工程链条。',output:'生命周期交付物表、需求到测试的最小映射',question:'哪些功能只有代码，哪些已经有同包验收？',access:'出版社书目与目录已核验；全文需合法购买或图书馆借阅。'},
  {id:'K02',kind:'教材',title:'Software Requirements · 3rd',author:'Karl Wiegers / Joy Beatty · Microsoft Press',topic:'需求与 PRD',priority:'先读',url:'https://www.microsoftpressstore.com/store/software-requirements-9780735679665',reading:'需求层次、干系人、获取与优先级、质量属性、变更管理；先读官方目录与样章。',use:'区分业务目标、用户任务、产品功能和非功能约束，避免把 PPT 愿景写成已实现功能。',output:'PRD 结构、用户故事、验收条件、范围变更表',question:'一次专注会话的成功是什么，谁有权接受这项需求？',access:'官方目录与样章可读；不是已通读全书。'},
  {id:'K03',kind:'教材',title:'Interaction Design · 6th',author:'Yvonne Rogers / Helen Sharp / Jennifer Preece · Wiley, 2023',topic:'用户体验',priority:'先读',url:'https://uat.store.wiley.com/en-us/interaction-design-beyond-human-computer-interaction-6th-edition-p-9781119901112',reading:'需求发现、概念模型、原型、用户研究与评估主题。',use:'把猫咪、地标、半页卡片放入可观察的用户任务，而不是只对齐像素。',output:'访谈提纲、旅程图、可用性测试脚本',question:'用户能否无提示找到开始、结束和会后建议？',access:'Wiley 书目与目录信息已检索核验；正式产品页直访 403，保留出版社索引入口。'},
  {id:'K04',kind:'教材',title:'Designing for Behavior Change · 2nd',author:'Stephen Wendel · O’Reilly, 2020',topic:'行为设计',priority:'先读',url:'https://www.oreilly.com/library/view/designing-for-behavior/9781492056027/',reading:'行动决策、行为设计流程、干预与效果评估主题。',use:'分析“想专注但未开始”的障碍；将自动专注、奖励、提醒当作待验证干预。',output:'目标行为定义、机制假设、实验草案',question:'猫咪提高专注意愿，还是增加了点按和分心？',access:'出版社目录已核验；全文需订阅或借阅。'},
  {id:'K05',kind:'教材',title:'Persuasive Technology',author:'B. J. Fogg · Morgan Kaufmann / Elsevier',topic:'行为设计',priority:'专题',url:'https://shop.elsevier.com/books/persuasive-technology/fogg/978-1-55860-643-2',reading:'计算机作为工具、媒介、社会角色，以及第 9 章劝导伦理。',use:'梳理虚拟猫的社会反馈、可信度与用户自主权。',output:'陪伴机制与退出自由设计原则',question:'自动进入专注是否可理解、可取消，奖励是否制造压力？',access:'出版社目录已核验；经典理论不等于本产品效果证据。'},
  {id:'K06',kind:'教材',title:'Game Feel',author:'Steve Swink · Routledge, 2009',topic:'交互与动画',priority:'专题',url:'https://www.routledge.com/Game-Feel-A-Game-Designers-Guide-to-Virtual-Sensation/Swink/p/book/9780123743282',reading:'实时控制、模拟空间、反馈与打磨主题。',use:'以动作可读性、接地、移动停止衔接和反馈时机审查猫咪，而不是仅检查 Animator 状态名。',output:'动作与反馈质量检查表、连续视频用例',question:'用户看见的动作是否和状态机声称的动作一致？',access:'出版社介绍已核验；动物运动解剖仍需另建真实参考库。'},
  {id:'K07',kind:'知识体系',title:'SWEBOK Guide · V4',author:'IEEE Computer Society',topic:'软件工程',priority:'先读',url:'https://www.computer.org/education/bodies-of-knowledge/software-engineering/resources/',reading:'18 个知识域作为覆盖检查；重点需求、架构、设计、构建、测试、质量、管理、安全、配置。',use:'检查生命周期覆盖，不把知识域机械变成强制串行瀑布流程。',output:'阶段覆盖表与裁剪理由',question:'哪些交付是项目真正需要，哪些只是照搬大团队形式？',access:'官方检索信息已核验；只链接官方入口，不在站内转载教材 PDF。'},
  {id:'K08',kind:'官方指南',title:'People + AI Guidebook',author:'Google PAIR',topic:'AI 体验',priority:'先读',url:'https://pair.withgoogle.com/guidebook-v2/',reading:'用户需求、AI 是否适用、解释、用户控制与失败处理。',use:'定义 AI 相对本地规则的额外价值，设计请求中、成功、失败三种可见状态。',output:'AI 功能契约与用户感知评估',question:'没有 MiMo 时核心体验是否完整，有 MiMo 时究竟多了什么？',access:'官方公开指南；不是模型效果评测结果。'},
  {id:'K09',kind:'官方指南',title:'Guidelines for Human-AI Interaction',author:'Microsoft HAX Toolkit',topic:'AI 体验',priority:'专题',url:'https://www.microsoft.com/en-us/haxtoolkit/ai-guidelines/',reading:'初次交互、交互中、出错时及长期交互的 18 条指南。',use:'明确模型能力边界、来源、可控性和低干扰反馈。',output:'AI 建议文案、来源标签、失败体验用例',question:'请求成功但猫咪反应不明显，算不算用户价值达成？',access:'官方公开指南；按适用性裁剪，不一律新增功能。'},
  {id:'K10',kind:'官方指南',title:'Core app quality guidelines',author:'Android Developers',topic:'移动质量',priority:'专题',url:'https://developer.android.com/docs/quality-guidelines/core-app-quality',reading:'用户体验、功能、兼容性与核心质量测试。',use:'补齐生命周期恢复、离线、权限、设备与发布验收。',output:'设备矩阵、核心流程回归与发布检查表',question:'模拟器通过之后，还有哪些只能在真机证明？',access:'官方页面已检索核验；发布平台要求应在提审前重新核验。'},
  {id:'K11',kind:'风险框架',title:'AI RMF · Generative AI Profile',author:'NIST · AI 600-1, 2024',topic:'AI 边界',priority:'专题',url:'https://www.nist.gov/itl/ai-risk-management-framework',reading:'生成式 AI 风险识别、测量和管理；只取适用于会后建议的项。',use:'防止建议越过非医疗陪伴边界；检查聚合数据上传、凭据与输出执行范围。',output:'小型 AI 评估集与风险处理表',question:'如何拒绝诊断式建议，以及如何不把模型文字直接变成任意动作？',access:'官方公开框架；不是中国发布合规结论。'}
].map(x=>({...x,checked:'2026-10-08',state:'书目 / 官方介绍已核验；待专题精读'}));

export const researchQuestions = [
  ['品类与目标人群','暂定数字健康 / 专注管理 × 虚拟宠物陪伴。学生是候选人群，不冒充已经通过访谈验证。','访谈样本、使用场景、现有替代方案'],
  ['行业与竞争','后续比较计时工具、游戏化专注、虚拟宠物、AI 陪伴四类；价格和功能必须带版本与日期。','官方功能 / 定价页、实际体验记录、评价抽样'],
  ['差异化与有效性','把“低压力陪伴能提高专注启动或完成”写成假设，不写成心理疗效或因果结论。','基线任务、可用性观察、访谈与后续实验'],
  ['PRD 的决策输入','确认目标人群、首发渠道、比赛 / 公开发布边界、成功指标、AI 成本与不做范围。','用户后续任务书与范围确认'],
  ['发布与隐私','先决定比赛私有演示还是公开上架；含本地凭据的候选 APK 不是公开发布包。','渠道规则、隐私文本、密钥部署方案、安全验收']
];
